version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Runnig hugo build...
      - docker run -v `pwd`/site:/src jguyomard/hugo-builder hugo
artifacts:
  files:
    - *
  base-directory: site/public/
