version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Runnig hugo build...
      - docker run -v `pwd`/site:/src jguyomard/hugo-builder hugo
  post_build:
    commands:
      - aws s3 sync site/public/ s3://3dhubs-tornike-test/hugo/
