version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Runnig hugo build...
      - docker run --rm -it -v (pwd)/site:/src -u hugo jguyomard/hugo-builder hugo
artifacts:
  files:
    - site/public/*
